CREATE TABLE request_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    applicant_id BIGINT NOT NULL,
    selected_offer_shift_id BIGINT,
    message VARCHAR(60),
    status VARCHAR(30) NOT NULL,
    decided_by BIGINT,
    reject_comment VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    CONSTRAINT fk_request_applications_request FOREIGN KEY (request_id) REFERENCES shift_requests (id),
    CONSTRAINT fk_request_applications_applicant FOREIGN KEY (applicant_id) REFERENCES users (id),
    CONSTRAINT fk_request_applications_selected_shift FOREIGN KEY (selected_offer_shift_id) REFERENCES shifts (id),
    CONSTRAINT fk_request_applications_decided_by FOREIGN KEY (decided_by) REFERENCES users (id),
    CONSTRAINT uq_request_applications_request_applicant UNIQUE (request_id, applicant_id),
    CONSTRAINT ck_request_applications_status CHECK (
        status IN ('PROPOSED', 'APPLIED', 'SELECTED', 'DECLINED', 'NOT_SELECTED', 'WITHDRAWN', 'REJECTED')
    )
);

CREATE INDEX idx_request_applications_applicant_status
    ON request_applications (applicant_id, status);

CREATE TABLE application_offer_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    shift_id BIGINT NOT NULL,
    CONSTRAINT fk_application_offer_shifts_application
        FOREIGN KEY (application_id) REFERENCES request_applications (id),
    CONSTRAINT fk_application_offer_shifts_shift
        FOREIGN KEY (shift_id) REFERENCES shifts (id),
    CONSTRAINT uq_application_offer_shifts_application_shift UNIQUE (application_id, shift_id)
);

CREATE INDEX idx_application_offer_shifts_shift ON application_offer_shifts (shift_id);
