CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    request_id BIGINT,
    store_id BIGINT,
    message VARCHAR(200) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_request FOREIGN KEY (request_id) REFERENCES shift_requests (id),
    CONSTRAINT fk_notifications_store FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT ck_notifications_type CHECK (
        type IN (
            'REQUEST_OPENED',
            'OPEN_SHIFT_POSTED',
            'PROPOSAL_RECEIVED',
            'APPLICATION_NEW',
            'APPROVAL_NEEDED',
            'CONFIRMED',
            'REJECTED',
            'EXPIRED',
            'MEMBER_REQUEST'
        )
    )
);

CREATE INDEX idx_notifications_user_read_created
    ON notifications (user_id, is_read, created_at DESC);
